import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.9,
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 20,
  },
  logoContainer: {
    alignSelf: 'center',
    marginBottom: 15,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    backgroundColor: '#f8f8f8',
  },
  logo: {
    width: 50,
    height: 50,
  },
  header: {
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: '#006400',
    borderWidth: 3,
    borderColor: '#333',
    borderRadius: 5,
    padding: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  text: {
    fontSize: 12,
    marginBottom: 20,
    marginHorizontal: 20,
    color: '#555',
    lineHeight: 24,
  },
  profileSection: {
    marginTop: 20,
  },
  profileHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 30,
    textAlign: 'center',
    color: '#006400',
    borderBottomWidth: 1,
  },
  profileContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  profileCard: {
    width: 225,
    height: 300,
    marginBottom: 20,
    marginHorizontal: 20,
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  profileImage: {
    width: '100%',
    height: '80%',
    marginBottom: 5,
  },
  profileName: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 5,
  },
  profileRole: {
    fontSize: 10,
    color: 'black',
  },
  socialContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    padding: 5,
    marginBottom: 15,
  },
  adminLinkContainer: {
    alignSelf: 'center',
    marginBottom: 70,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    backgroundColor: '#f8f8f8',
  },
});

export default styles;
