import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
    height: "100%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto",
  },
  imageOpacity: {
    opacity: 0.15,
  },
  container: {
    flex: 1,
  },
  scrollViewContainer: {
    flex: 1,
  },
  scrollViewContent: {
    padding: 20,
  },
  header: {
    width: "100%",
    height: 20,
    backgroundColor: "#013220",
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 1,
  },
  headerOptions: {
    flexDirection: "row",
    justifyContent: "space-around",
    flexWrap: "wrap",
    width: "100%",
    marginHorizontal: 5,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    marginRight: 40,
    marginTop: 40,
  },
  logo: {
    width: 50,
    height: 50,
    marginRight: 15,
    marginBottom: 5,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    backgroundColor: "#f8f8f8",
  },
  searchBar: {
    flex: 1,
    borderColor: "black",
    borderWidth: 2,
    borderRadius: 5,
    padding: 10,
    backgroundColor: "rgba(245, 245, 220, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  searchIcon: {
    marginLeft: -30,
  },
  disclaimerContainer: {
    padding: 10,
    backgroundColor: 'rgba(245, 245, 220, 0.3)',
    borderWidth: 1,
    borderColor: "#006400",
  },
  disclaimerText: {
    fontSize: 10,
    color: "black",
    textAlign: "center",
    marginHorizontal: 10,
    marginBottom: 30,
    fontWeight: "300",
  },
  content: {
    flex: 1,
    padding: 20,
  },
  scrollViewContent: {
    flexGrow: 1,
  },
  tagline: {
    fontWeight: 500,
    textAlign: "center",
    marginBottom: 30,
    backgroundColor: "rgba(245, 245, 245, 0.5)",
    borderRadius: 5,
    padding: 10,
  },
  productList: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    columnGap: 15,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    flexDirection: "row",
    backgroundColor: 'rgba(240, 255, 240, 0.9)',
    padding: 20,
    borderRadius: 10,
    width: "80%",
    height: "60%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  modalLeftContent: {
    width: "60%",
    justifyContent: "space-between",
  },
  modalImage: {
    width: "95%",
    height: "80%",
    borderRadius: 10,
    borderWidth: 0.5,
  },
  modalButtonContainer: {
    flexDirection: "column",
    justifyContent: "flex-start",
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    backgroundColor: "#006400",
    padding: 8,
    borderRadius: 10,
    marginHorizontal: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  modalButtonText: {
    color: "#fff",
    fontSize: 12,
  },
  modalCloseButton: {
    flex: 1,
    backgroundColor: "red",
    padding: 8,
    borderRadius: 10,
    marginHorizontal: 50,
    alignItems: "center",
    marginTop: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalCloseButtonText: {
    color: "#fff",
    fontSize: 12,
  },
  modalTextContainer: {
    width: "40%",
    paddingLeft: 5,
    paddingRight: 5,
    justifyContent: "top",
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 10,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    overflow: "hidden",
  },
  modalName: {
    fontSize: 15,
    fontWeight: 400,
    textTransform: "uppercase",
    marginBottom: 5,
    textAlign: "center",
  },
  modalPrice: {
    fontWeight: "bold",
    color: "#006400",
    marginBottom: 5,
    textAlign: "center",
  },
  modalDescription: {
    fontWeight: 200,
    textAlign: "center",
  },
});

export default styles;