import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  imageOpacity: {
    opacity: 0.25,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    padding: 20,
    borderColor: "#006400",
    borderWidth: 2,
    borderRadius: 10,
    margin: 20,
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.3)",
  },
  logoContainer: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 2,
    borderColor: "#006400",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.7)",
  },
  logo: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  titleText: {
    fontFamily: "Georgia, sans-serif",
    fontSize: 84,
    fontWeight: "bold",
    color: "#006400",
    marginBottom: 5,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  titleHeader: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#006400",
    marginBottom: 30,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  subtitleText: {
    fontSize: 24,
    fontWeight: "600",
    color: "#006400",
    marginBottom: 60,
    textAlign: "center",
    textTransform: "uppercase",
  },
  hawaiianText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#006400",
    textAlign: "center",
    borderColor: "#006400",
    padding: 10,
    marginBottom: 20,
  },
  messageText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#006400",
    textAlign: "center",
    borderColor: "#006400",
    padding: 10,
  },
});

export default styles;