name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Step to install dependencies
      - run: npm install
      
      # Run Expo export to generate a build in the dist directory
      - run: npx expo export
      
      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      # Deploy the build to Firebase Hosting Preview Channel
      - name: Deploy to Firebase Hosting Preview Channel
        run: |
          firebase hosting:channel:deploy preview --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

